---
- hosts: all
  become: true

  vars:
    apache_port: 7777
    deb: "Debian"
    rh: "RedHat"

  tasks:
  - name: installation of apache server on {{deb}} based server
    apt: name=apache2 state=installed
    when: ansible_os_family == "{{deb}}"
    notify: restarting apache

  - name: installation of apache server on {{rh}} based server
    yum: name=httpd state=installed
    when: ansible_os_family == "{{rh}}"
    notify: restarting httpd

  - name: changing the apache port on {{deb}} server
    template:
      src: templates/ports.conf.j2
      dest: /etc/apache2/ports.conf
    notify: restarting apache
    when: ansible_os_family == "{{deb}}"

  - name: changing the httpd port on {{rh}} server
    template:
      src: templates/httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    notify: restarting httpd
    when: ansible_os_family == "{{rh}}"

  handlers:
    - name: restarting apache
      service: name=apache2 state=restarted

    - name: restarting httpd
      service: name=httpd state=restarted
